---
name: QA Checks Only

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
      - '!tests/**'

jobs:
  lint-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install QA tools
        run: |
          pip install black flake8 isort

      - name: Run Black
        run: |
          black --check .

      - name: Run Flake8
        run: |
          flake8 .

      - name: Run isort
        run: |
          isort --check-only .
